name:                crytopals-solutions
version:             0.1.0.0
github:              "xaviershay/crytopals-solutions"
license:             BSD3
author:              "Xavier Shay"
maintainer:          "contact@xaviershay.com"
copyright:           "2018 Xavier Shay"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/crytopals-solutions#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  crytopals-solutions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crytopals-solutions

tests:
  crytopals-solutions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crytopals-solutions
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    - bytestring
    - containers
